version: '3'

volumes:
    customer_postgres_data:
        driver: local

services:
    postgres:
        container_name: spring-boot-postgres_container
        image: postgres:13.3
        volumes:
            - customer_postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

    customer-management-service:
        container_name: customer-management-service
        image: larmic/szut-customer-management-service:latest
        environment:
            spring.datasource.url: jdbc:postgresql://spring-boot-postgres_container:5432/${POSTGRES_DB}
            spring.datasource.username: ${POSTGRES_USER}
            spring.datasource.password: ${POSTGRES_PASSWORD}
        ports:
            - "8083:8083"
        depends_on:
            - postgres